github:
  is_project_page: false
theme: jekyll-theme-minimal
title: Quang
description: Hi! This is a page where I shall tell you about all of my achievements and activities, just in case if resumés become a thing of the past. 
logo: https://i.imgur.com/YCpV2zM.jpg
